honest-cash/honestcash

public/templates/layout.html
public/templates/partials/profile-badge.html
src/core/style.css

- added balance bar to mobile
- this also addresses the obscurity of being logged in or not in mobile (you will have balance bar visible if logged in)

- added balance bar to mobile

---

src/app/components/uncensorable-button/uncensorable-button.component.ts

* Changed the extUri to honest.cash/post/$postId, as this is much shorter, but gives the same result

Fix metadata being too large for bitcoinfiles

---

public/templates/profile-edit.html
public/templates/profile.html
src/app/components/index.js
src/app/components/simple-ledger-protocol-details/simple-ledger-protocol-details.component.ts
src/app/components/simple-ledger-protocol-details/simple-ledger-protocol-details.styles.less
src/app/components/simple-ledger-protocol-details/simple-ledger-protocol-details.template.html
src/app/controllers/ProfileCtrl.ts
src/app/controllers/ProfileEditCtrl.ts
src/core/models/models.ts
src/core/services/BitcoinComService.ts
src/core/services/ProfileService.ts
src/core/services/index.ts

- added BitcoinComService in case it is used in the future
- the badge as a directive with multiple color backgrounds in case it is used for other kind of badges

feat(profile): added SLP balance to the profile

---

public/templates/post.html
src/app/controllers/PostCtrl.ts

refactor(response-ordering): refactored response ordering to use orderBy of angular

refactor(response-ordering)

---

src/app/styles/post.css

hopefully the same method for feed-body works for response-body

fix(responses): fixed body overflowing

---

public/templates/new-login.html
public/templates/welcome.html
src/welcome/welcome.css

welcome: remove artist name

---

public/templates/feeds.html
public/templates/thankyou.html
src/auth/AuthModule.ts
src/auth/AuthService.ts
src/core/lib/logger.ts
src/core/runs/runs.ts
src/core/style.css
src/welcome/WelcomeCtrl.ts
src/welcome/welcome.css

Creations of an account does not longer puts on on the waiting list but directly forwards you to the feed. The wallet is generated also on signup.

Public registrations

---

public/templates/posts.html
src/editor/EditorCtrl.ts
src/editor/editor.ts
src/editor/services/EditorService.ts

- fixes body of posts in /posts page
- fixed the paid section body not being posted in put request
- fixed nth-child problem

fix of paid section and posts page

---

public/templates/profile.html
src/app/components/follow-unfollow-button/follow-unfollow-button.component.ts
src/app/components/follow-unfollow-button/follow-unfollow-button.template.html
src/app/controllers/ProfileCtrl.ts

- made follow-unfollow button more stable,
- it has also been added to profile page (the old one was not working)

made follow-unfollow button more stable,

---

src/app/components/follow-unfollow-button/follow-unfollow-button.component.ts

added additional check to prevent following self

added additional check to prevent following self

---

package.json
public/templates/layout_write.html
src/editor/EditorCtrl.ts
typings.d.ts

- made webpack hot-reload with watch; this means that you run `npm run watch` and in another cmd `npm start` to have it recompile on save, you need to refresh your page,
- added missing modules to typings.d.ts to silence the errors,
- fixed all linting in editorctrl,
- added min value of 0.001 and max value of 1 bch to paid section cost
- removed pre commit because it does not work yet (I at the moment use a client for git, it does not have commit -n so I removed the linter on precommit for now. I will gradually fix all linting errors (there are alot if you check npm run watch logs) or spend some time later to fix them all at once

Paywall bug: 0.0005 BCH is displayed as 0 BCH. 

---

src/app/components/follow-unfollow-button/follow-unfollow-button.component.ts

fixed undefined error

---

public/templates/layout.html
public/templates/partials/profile-badge.html
public/templates/settings.html
src/app/app.ts
src/app/controllers/SettingsCtrl.ts
src/app/stateConfig.js
src/core/services/ProfileService.ts

added settings page along with the following settings for e-mail subscription:
followingNewStory for following people that publish a new story
weeklyDigest for weekly digest

subscription settings for emails

---

honestcash-v2/package-lock.json
honestcash-v2/src/app/core/store/auth/auth.effects.ts
src/core/runs/runs.ts

fixed simpleWallet being undefined for already registered users (when they reset password)

fix(login):

---

honestcash-v2/src/app/core/services/authentication.service.ts
honestcash-v2/src/app/modules/welcome/components/loading-submit-button/loading-submit-button.component.html
honestcash-v2/src/app/modules/welcome/pages/reset-password-verify/reset-password-verify.component.html

fixed form not submitting when passwords match
make sure to merge to `master` aswell

fix(reset-password):

---

honestcash-v2/src/app/modules/editor/components/editor/editor.component.scss

hidden h1, h4, h5, h6 headings of editor (by css)

hidden h1, h4, h5 and h6 headings from editor

---

honestcash-v2/src/app/modules/editor/components/save-status/save-status.component.ts

fixed auto save functionality being fired twice or prematurely or out of sync

fix(editor): auto save

---

honestcash-v2/src/app/app.component.scss
honestcash-v2/src/app/modules/editor/components/editor/editor.component.html
honestcash-v2/src/app/modules/editor/components/editor/editor.component.scss
honestcash-v2/src/app/modules/editor/components/editor/editor.component.ts
honestcash-v2/src/app/modules/editor/components/loading-indicator/loading-indicator.component.html
honestcash-v2/src/app/modules/editor/components/loading-indicator/loading-indicator.component.scss
honestcash-v2/src/app/modules/editor/components/loading-indicator/loading-indicator.component.spec.ts
honestcash-v2/src/app/modules/editor/components/loading-indicator/loading-indicator.component.ts
honestcash-v2/src/app/modules/editor/editor-container.component.scss
honestcash-v2/src/app/modules/editor/editor.module.ts
honestcash-v2/src/app/modules/editor/pages/edit/edit.component.scss
honestcash-v2/src/app/modules/editor/pages/story-preview/story-preview.component.scss
honestcash-v2/src/app/modules/editor/pages/write/write.component.scss
honestcash-v2/src/styles.scss

added Honest logo as loading indicator until editor is loaded completely

HC-167 / added editor loading indicator (honest logo)

---

honestcash-v2/src/app/modules/editor/services/editor.service.ts

- fixed paidSection being always true (leftover code from development/testing)
another PR with same branch name outstands for the backend aswell (although they are not related, it contains fix that are overlooked for comments)

HC-170 / Fix of publish button

---

honestcash-v2/src/app/shared/components/honest-logo/honest-logo.component.html

fix(honest-logo): fixed honest logo being broken due to absolute path

HC-174 / Honest logo in editor header was broken due to absolute path

---

honestcash-v2/src/app/modules/editor/components/paid-section-selection/paid-section-selection.component.html

- removed font size and margin info at the bottom of paid section selection

HC-175 / removal of info at the bottom of paid section selection

---

honestcash-v2/src/app/modules/editor/components/editor/editor.component.html
honestcash-v2/src/app/modules/editor/components/editor/editor.component.ts
honestcash-v2/src/app/modules/editor/components/save-status/save-status.component.ts
honestcash-v2/src/app/modules/editor/services/editor.service.ts
honestcash-v2/src/app/store/editor/editor.effects.ts
honestcash-v2/src/app/store/editor/editor.reducer.ts

- fix title not triggering auto save,
- made autosave cover title to be saved aswell,
- fixed a bug where your already set title was not visible in title area
requires blocking PR on backend with the same title `HC-165 / title is now triggering autoSave`.

HC-165 / title is now triggering autoSave

---

honestcash-v2/src/app/modules/editor/components/editor/editor.component.ts

- fix of links (by removing link tool so that bare links are used)
- removal of code block (it was not visible already but no reason to keep it in code, it can be added when needed)

NO TASK / fix links in editor

---

honestcash-v2/src/app/modules/editor/components/embeddable-editor/embeddable.component.scss
honestcash-v2/src/app/modules/editor/components/publish-modal/publish-modal.component.scss

- refactored scss files to leverage SASS
- also made tags input to be inline

HC-178 / tags inline

---

app.js
honestcash-v2/src/app/modules/editor/components/editor/editor.component.ts
honestcash-v2/src/app/modules/editor/components/parent-post-body/parent-post-body.component.scss
src/app/post/post.html

- I had previously changed the ng-href in another PR to editor/comment thinking it would work so I reverted it to /write/response/:parentPostId so that it successfully goes to that route to be picked up by app.js route
- added comment route to app.js to redirect to /v2/editor/comment/:parentPostId

fix(post): fixed response links

---

honestcash-v2/src/app/modules/editor/components/paid-section-selection/paid-section-selection.component.html

- changed paywall text to `Choose your paywall content by selecting what's inside the green outline using the up and down arrows.`

HC-179 / change of paywall description text

---

honestcash-v2/src/app/modules/editor/components/paid-section-selection/paid-section-selection.component.html

- changed paywall cost slider value color to green
- and added a dollar sign

HC-199 / paywall cost dollar sign and color

---

honestcash-v2/src/app/modules/editor/components/publish-modal/publish-modal.component.spec.ts
honestcash-v2/src/app/modules/editor/components/publish-modal/publish-modal.component.ts
honestcash-v2/src/app/modules/editor/components/save-status/save-status.component.spec.ts
honestcash-v2/src/app/modules/editor/components/save-status/save-status.component.ts
honestcash-v2/src/app/modules/editor/components/story-tags-selection/story-tags-selection.component.html
honestcash-v2/src/app/modules/editor/components/story-tags-selection/story-tags-selection.component.spec.ts
honestcash-v2/src/app/modules/editor/components/story-tags-selection/story-tags-selection.component.ts
honestcash-v2/src/app/shared/models/hashtag.ts

- added remaining tests
the only thing that is not tested is **auto save functionality** (it will take some time for me to experiment the test case with takeWhile however the tests does not need to be written for now)

HC-132 / tests for editor stage 2

---

honestcash-v2/src/app/story/components/share-buttons/story-share-buttons.component.html
honestcash-v2/src/app/story/components/share-buttons/story-share-buttons.component.ts
honestcash-v2/src/app/story/models/story.ts
honestcash-v2/src/app/story/store/story.reducer.ts
honestcash-v2/src/core/shared/modules/font-awesome.module.ts

- sharing links (reddit and twitter only) are now functional

HC-224 / made share links functional

---

app.js
honestcash-v2/src/app/app-routing.module.ts

- added redirect routes to v2 story page

HC-232 / v1 routing for v2 story

---

honestcash-v2/src/app/story/components/comment-card-body/story-comment-card-body.component.scss

- fixed max-width on images in story comments (this will affect only the old comments because new comments only have text, no ability to add image)

HC-227 / fix image width in comments

---

honestcash-v2/package-lock.json
honestcash-v2/package.json
honestcash-v2/src/app/story/components/comments/story-comments.component.html
honestcash-v2/src/app/story/components/comments/story-comments.component.ts
honestcash-v2/src/app/story/story.module.ts

- sorting only applies to the first level of comments (not comments inside comments, they are still sorted by createdAt)

HC-226 / added sorting to comments

---

honestcash-v2/src/app/story/models/story.ts
honestcash-v2/src/app/story/story.component.ts

- added og:image and twitter:image change to story.imageURL as well title of the page to story title
it needs to be deployed to beta so we test

NO TASK / story seo og and twitter image tags and page title of story

---

honestcash-v2/src/app/story/components/comment-card-actions/comment-card-actions.component.html
honestcash-v2/src/app/story/components/comment-card/story-comment-card.component.html
honestcash-v2/src/app/story/components/comment-card/story-comment-card.component.scss
honestcash-v2/src/app/story/components/comment-card/story-comment-card.component.ts
honestcash-v2/src/app/story/components/comment-counts/story-counts.component.html
honestcash-v2/src/app/story/components/comment-counts/story-counts.component.scss
honestcash-v2/src/app/story/components/comment-counts/story-counts.component.ts
honestcash-v2/src/app/story/components/comment-edit-button/comment-edit-button.component.html
honestcash-v2/src/app/story/components/comment-edit-button/comment-edit-button.component.ts
honestcash-v2/src/app/story/components/comment-inline-editor/story-comment-inline-editor.component.html
honestcash-v2/src/app/story/components/comment-inline-editor/story-comment-inline-editor.component.scss
honestcash-v2/src/app/story/components/comment-inline-editor/story-comment-inline-editor.component.ts
honestcash-v2/src/app/story/components/comments/story-comments.component.ts
honestcash-v2/src/app/story/services/story.service.ts
honestcash-v2/src/app/story/shared/story.endpoints.ts
honestcash-v2/src/app/story/store/story.actions.ts
honestcash-v2/src/app/story/store/story.effects.ts
honestcash-v2/src/app/story/store/story.reducer.ts
honestcash-v2/src/app/story/store/story.state.ts
honestcash-v2/src/app/story/story.module.ts
honestcash-v2/src/core/shared/modules/font-awesome.module.ts

- also made additions and changes flash so that they are morely noticable
- scroll should be kind of in the middle or below middle but not at the very top, it was always almost at the very top so this should improve it

HC-236 / comment inline editing
